import "../styles/globals.css";
import Head from "next/head"

function MyApp({ Component, pageProps }) {
  return <>
  <Head>
        <title>Tiger Group</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐯</text></svg>"
          type="image/x-icon"
        />
      </Head>
  <Component {...pageProps} />
  </>;
}

export default MyApp;
